<?php
namespace backend\controllers;

use tsingsun\swoole\server\Server;
use Yii;
use yii\web\Controller;

Class TestsController extends Controller {

    public $enableCsrfValidation = false;
    public $serv;
    const  HOST = "0.0.0.0";
    const  PORT = "9501";
    public function init()
    {
        \Yii::$app->user->enableSession = false;
        $this->serv = parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
//        $behaviors['authenticator'] =[
//            'class'=>QueryParamAuth::className(),
//        ];
        return $behaviors;
    }

//    public function __construct()
//    {
//        $this->serv = new swoole_websocket_server();
//    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionOpen()
    {
        $serv = $this->init();

        var_dump($serv);
    }

    public function actionMessage($frame)
    {

        return rand(100,1000);
    }

    public function actionClose()
    {
        return 'close';
        /** @var Application */

    }
}